name: Erlang CI

on: push

concurrency:
  group: erlang-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build and tests
    runs-on: ubuntu-latest

    strategy:
      matrix:
        erlang: ['26-slim']

    services:
      memcached:
        image: adgear-docker.jfrog.io/adgear/actions-delivery-memcached:1.6.21-bookworm
        ports:
          - '11211:11211'

    steps:
      - name: Clone project
        uses: actions/checkout@v4

      - name: Cache
        uses: actions/cache@v3
        env:
          cache-name: rebar3
        with:
          path: |
            _build
            ~/.cache/rebar3
          key: ci-${{runner.os}}-${{env.cache-name}}-erlang_${{matrix.erlang}}-rebar3-${{hashFiles('rebar.lock')}}

      - name: Fetch dependencies
        run: rebar3 get-deps

      - name: Format checks
        run: make fmt-check

      - name: Build
        run: make compile

      - name: Eunit checks
        run: make eunit

      - name: xref checks
        run: make xref

      - name: Dialyzer checks
        run: make dialyzer